In [38]:
import psycopg2

In [54]:
conn1 = psycopg2.connect(dsn="postgresql://user2:password@localhost:25432/database02")

In [55]:
cur = conn1.cursor()

In [56]:
cur.execute("""
CREATE USER pgbouncer_auth WITH PASSWORD 'super_secret_auth_pw';
""")

In [57]:
cur.execute("""
CREATE OR REPLACE FUNCTION user_lookup(in_user text, out uname text, out phash text)
RETURNS record AS $$
    SELECT usename, passwd FROM pg_shadow WHERE usename = in_user;
$$ LANGUAGE sql SECURITY DEFINER;
""")

In [58]:
cur.execute("""
REVOKE ALL ON FUNCTION user_lookup(text) FROM public;
GRANT EXECUTE ON FUNCTION user_lookup(text) TO pgbouncer_auth;
""")

In [59]:
conn1.commit()

In [60]:
import pandas as pd

In [77]:
con = "postgresql://user:password@localhost:6432/db1"
con

'postgresql://user:password@localhost:6432/db1'

In [78]:
pd.read_sql_query("""
SELECT * FROM information_schema.tables
""", con)

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,database01,public,table-db01,BASE TABLE,None,None,None,None,None,YES,NO,None
1,database01,pg_catalog,pg_statistic,BASE TABLE,None,None,None,None,None,YES,NO,None
2,database01,pg_catalog,pg_type,BASE TABLE,None,None,None,None,None,YES,NO,None
3,database01,pg_catalog,pg_foreign_table,BASE TABLE,None,None,None,None,None,YES,NO,None
4,database01,pg_catalog,pg_authid,BASE TABLE,None,None,None,None,None,YES,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...
209,database01,information_schema,foreign_table_options,VIEW,None,None,None,None,None,NO,NO,None
210,database01,information_schema,foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
211,database01,information_schema,_pg_user_mappings,VIEW,None,None,None,None,None,NO,NO,None
212,database01,information_schema,user_mapping_options,VIEW,None,None,None,None,None,NO,NO,None
213,database01,information_schema,user_mappings,VIEW,None,None,None,None,None,NO,NO,None

In [71]:
con_db1 = "postgresql://user:password@localhost:6432/db1"
con_db2 = "postgresql://user2:password@localhost:6432/db2"

In [72]:
df1 = pd.DataFrame([{'database': "01"}])
df1

  database
0       01

In [73]:
df2 = pd.DataFrame([{'database': "02"}])
df2

  database
0       02

In [74]:
df1.to_sql(name='table-db01', con=con_db1)

1

In [75]:
df2.to_sql(name='table-db02', con=con_db2)

1